if [ "${BASH-no}" != "no" ]; then
    [ -r ~/.bashrc ] && . ~/.bashrc
fi

. ./.bashrc

# added by Anaconda2 installer
# export path
export PATH="/Users/lance/anaconda2/bin:$PATH"
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/lance/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/lance/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/lance/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/lance/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda deactivate

PATH=$PATH:$HOME/bin:/sbin:/usr/bin:/usr/sbin
